import pandas as pd

def blend_submissions():
    # Use v3 as the trusted baseline
    sf = pd.read_csv('submission_ultimate_v3.csv', keep_default_na=False)
    # The new predictions generated by Moondream locally
    sm = pd.read_csv('submission_moondream_local_25percent.csv', keep_default_na=False)
    test = pd.read_csv('test_qa.csv')
    
    sf_dict = dict(zip(sf['qa_id'], sf['prediction']))
    sm_dict = dict(zip(sm['qa_id'], sm['prediction']))
    
    final_preds = []
    changes = 0
    
    for idx, row in test.iterrows():
        qa_id = row['qa_id']
        cat = row['category']
        
        f_pred = str(sf_dict.get(qa_id, 'A')).upper()
        # Moondream may not have processed this file if it wasn't multi/sequence
        m_pred = str(sm_dict.get(qa_id, f_pred)).upper()
        
        if f_pred in ['NA', 'NAN', '']:
            final_pred = m_pred
            changes += 1
        elif cat == 'multi' and qa_id in sm_dict:
            # Trust Moondream to add missing letters, but keep the baseline's core guess
            combined = set(f_pred) | set(m_pred)
            combined_pred = "".join(sorted([c for c in combined if c in 'ABCD']))
            
            if len(combined_pred) == 0: combined_pred = 'A'
            final_pred = combined_pred
            
            if final_pred != f_pred:
                changes += 1
        elif cat == 'sequence' and qa_id in sm_dict:
            # Sequence: Just trust Moondream completely
            final_pred = m_pred
            if final_pred != f_pred:
                changes += 1
        else:
            final_pred = f_pred
            
        final_preds.append({'qa_id': qa_id, 'prediction': final_pred})
        
    df_out = pd.DataFrame(final_preds)
    df_out.to_csv('submission_ultimate_v6.csv', index=False)
    print(f"Created submission_ultimate_v6.csv with {changes} strategic overrides from Moondream!")

if __name__ == '__main__':
    blend_submissions()
